version: '3.8'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src/main/webapp:/static
      - ./docs/help:/docs
    depends_on:
      - app
      - docs
    ports:
      - '80:80'
      - '8081:8081'
    networks:
      - frontend

  app:
    container_name: app
    build: .
    networks:
      - frontend
      - backend
    depends_on:
      mysql:
        condition: service_healthy 

  docs:
    build:
      context: .
      dockerfile: docs.Dockerfile
    networks:
      - frontend
      - backend

  mysql:
    image: mysql:5.7
    volumes:
      - data:/var/lib/mysql
      - ./datadump:/docker-entrypoint-initdb.d
    networks:
      - backend
    environment:
       MYSQL_ROOT_PASSWORD: 12345
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-uroot', '-p12345']
      interval: 5s
      timeout: 5s
      retries: 10 

networks:
  frontend:
  backend:

volumes:
  data:
